export enum CompanyActionTypes {
    FETCH_COMPANIES = 'FETCH_COMPANIES',
    FETCH_COMPANIES_SUCCESS = 'FETCH_COMPANIES_SUCCESS',
    FETCH_COMPANIES_FAIL = 'FETCH_COMPANIES_FAIL',
    FETCH_COMPANY = 'FETCH_COMPANY',
    FETCH_COMPANY_SUCCESS = 'FETCH_COMPANY_SUCCESS',
    FETCH_COMPANY_FAIL = 'FETCH_COMPANY_FAIL',
    ADD_COMPANY = 'ADD_COMPANY',
    ADD_COMPANY_SUCCESS = 'ADD_COMPANY_SUCCESS',
    ADD_COMPANY_FAIL = 'ADD_COMPANY_FAIL',
    EDIT_COMPANY = 'EDIT_COMPANY',
    EDIT_COMPANY_SUCCESS = 'EDIT_COMPANY_SUCCESS',
    EDIT_COMPANY_FAIL = 'EDIT_COMPANY_FAIL',
    DELETE_COMPANY = 'DELETE_COMPANY',
    DELETE_COMPANY_SUCCESS = 'DELETE_COMPANY_SUCCESS',
    DELETE_COMPANY_FAIL = 'DELETE_COMPANY_FAIL'
}

export enum AuthActionTypes {
    AUTH_START = 'AUTH_START',
    AUTH_SUCCESS = 'AUTH_SUCCESS',
    AUTH_FAIL = 'AUTH_FAIL',
}

export enum AlertActionTypes {
    OPEN_ALERT_MODAL = 'OPEN_ALERT_MODAL',
    TOGGLE_ALERT_MODAL = 'TOGGLE_ALERT_MODAL',
}